#!/usr/bin/env python3
"""Convert one or more 15x15 1-bit PNGs into a C header of QuickDraw bitmaps.

Usage:
    scripts/png-to-toolbar-icons.py <out.h> <icon1.png> [icon2.png ...]

Each PNG becomes a `static const unsigned char kIcon_<stem>[]` array
laid out for a 15x15 BitMap with rowBytes=2 (15 bits per row stored
MSB-first into a 16-bit word, low bit padded with 0). A pixel is
"black" if its grayscale value is < 128.

The C symbol is derived from the file stem with '-' → '_'.
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.stderr.write("error: Pillow not installed. Try: pip3 install Pillow\n")
    sys.exit(1)


def png_to_rows(path: Path, w: int = 15, h: int = 15) -> list[int]:
    """Return h shorts, one per row, with bits MSB-first (bit 15 = x=0)."""
    img = Image.open(path).convert("L")
    if img.size != (w, h):
        sys.stderr.write(f"error: {path}: expected {w}x{h}, got {img.size[0]}x{img.size[1]}\n")
        sys.exit(1)
    px = img.load()
    rows = []
    for y in range(h):
        word = 0
        for x in range(w):
            if px[x, y] < 128:
                word |= 1 << (15 - x)
        rows.append(word)
    return rows


def emit(out_path: Path, pngs: list[Path]) -> None:
    lines = [
        "/* Auto-generated by scripts/png-to-toolbar-icons.py — do not edit. */",
        "#ifndef MACDOWN_TOOLBAR_ICONS_H",
        "#define MACDOWN_TOOLBAR_ICONS_H",
        "",
        "#define kToolbarIconSize     15",
        "#define kToolbarIconRowBytes 2",
        "",
        "/* Rows stored as `unsigned short` (not `unsigned char[]`) so the",
        "   linker word-aligns the data: CopyBits accesses bitmap rows with",
        "   MOVE.W, which bus-errors on real 68000s if baseAddr is odd. */",
        "",
    ]
    for p in pngs:
        sym = "kIcon_" + p.stem.replace("-", "_")
        rows = png_to_rows(p)
        lines.append(f"/* {p.name} */")
        lines.append(f"static const unsigned short {sym}[{len(rows)}] = {{")
        for i in range(0, len(rows), 5):
            chunk = rows[i:i + 5]
            lines.append("    " + ", ".join(f"0x{r:04X}" for r in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines.append("#endif")
    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    if len(sys.argv) < 3:
        sys.stderr.write(__doc__)
        return 2
    out_path = Path(sys.argv[1])
    pngs = [Path(p) for p in sys.argv[2:]]
    emit(out_path, pngs)
    return 0


if __name__ == "__main__":
    sys.exit(main())
