/* Auto-generated by scripts/png-to-toolbar-icons.py — do not edit. */
#ifndef MACDOWN_TOOLBAR_ICONS_H
#define MACDOWN_TOOLBAR_ICONS_H

#define kToolbarIconSize     15
#define kToolbarIconRowBytes 2

/* Rows stored as `unsigned short` (not `unsigned char[]`) so the
   linker word-aligns the data: CopyBits accesses bitmap rows with
   MOVE.W, which bus-errors on real 68000s if baseAddr is odd. */

/* folder-up-15px.png */
static const unsigned short kIcon_folder_up_15px[15] = {
    0x0000, 0x0000, 0x0E00, 0x1100, 0x3FF8,
    0x4004, 0x4104, 0x4384, 0x47C4, 0x4104,
    0x4104, 0x4004, 0x7FFC, 0x0000, 0x0000,
};

/* folder-open-15px.png */
static const unsigned short kIcon_folder_open_15px[15] = {
    0x0000, 0x0000, 0x1C00, 0x2200, 0x7FF0,
    0x8008, 0x9FFE, 0x9002, 0xA004, 0xA004,
    0xA004, 0xC008, 0xFFF8, 0x0000, 0x0000,
};

/* folder-new-15px.png */
static const unsigned short kIcon_folder_new_15px[15] = {
    0x0000, 0x0000, 0x0E00, 0x1100, 0x3FF8,
    0x4004, 0x4104, 0x4104, 0x47C4, 0x4104,
    0x4104, 0x4004, 0x7FFC, 0x0000, 0x0000,
};

/* trash-15px.png */
static const unsigned short kIcon_trash_15px[15] = {
    0x0000, 0x0380, 0x3FF8, 0x1010, 0x1550,
    0x1550, 0x1550, 0x1550, 0x1550, 0x1550,
    0x1550, 0x1550, 0x1010, 0x0FE0, 0x0000,
};

#endif
